# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-14 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=5)),
                ('roomBlock', models.CharField(max_length=40)),
                ('roomFloor', models.IntegerField()),
            ],
        ),
    ]
