# Generated by Django 2.0.3 on 2018-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0006_auto_20180915_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('branches', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='brandsec',
            name='branches',
        ),
        migrations.AddField(
            model_name='brandsec',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brandsec',
            name='branchName',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='brandsec',
            name='branchSec',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='brandsec',
            name='sectionCapacity',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
