# Generated by Django 2.0.3 on 2018-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0007_auto_20180915_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='deptAndSec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfDepts', models.CharField(default=' ', max_length=3)),
                ('nameOfDept', models.CharField(default=' ', max_length=20)),
                ('sectionsInDept', models.CharField(default=' ', max_length=4)),
                ('secName', models.CharField(default=' ', max_length=8)),
                ('secCapacity', models.CharField(default=' ', max_length=8)),
                ('startingRoll', models.CharField(default=' ', max_length=15)),
                ('endingRoll', models.CharField(default=' ', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='branches',
        ),
        migrations.DeleteModel(
            name='brAndSec',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='roomBlock',
        ),
        migrations.RemoveField(
            model_name='classrooms',
            name='roomFloor',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='noOfRooms',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='roomid',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
