# Generated by Django 2.0.3 on 2018-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0009_auto_20181004_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addanddel',
            name='addNum',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='addanddel',
            name='addNumRoll',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='addanddel',
            name='delNum',
            field=models.CharField(blank=True, default=' ', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='addanddel',
            name='delNumRoll',
            field=models.CharField(blank=True, default=' ', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='noOfRooms',
            field=models.CharField(blank=True, default=' ', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room1',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room10',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room2',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room3',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room4',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room5',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room6',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room7',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room8',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='room9',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section1',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section10',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section2',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section3',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section4',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section5',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section6',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section7',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section8',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='deptandsec',
            name='section9',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
