# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-14 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrooms',
            name='roomFloor',
            field=models.CharField(max_length=1),
        ),
    ]
