# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-14 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0002_auto_20180914_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='addAndDel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addNum', models.CharField(max_length=3)),
                ('addNumRoll', models.CharField(max_length=15)),
                ('delNum', models.CharField(max_length=3)),
                ('delNumRoll', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='brAndSec',
            fields=[
                ('branches', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('branchToSections', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='secCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionCapacity', models.CharField(max_length=5)),
                ('branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createArrangement.brAndSec')),
            ],
        ),
    ]
