# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-14 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0003_addanddel_brandsec_seccap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seccap',
            name='branches',
        ),
    ]
