# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0004_remove_seccap_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='capacity',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='cols',
            field=models.CharField(default=' ', max_length=2),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='rows',
            field=models.CharField(default=' ', max_length=2),
        ),
    ]
