# Generated by Django 2.0.3 on 2018-10-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createArrangement', '0010_auto_20181004_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addanddel',
            name='addNum',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='addanddel',
            name='addNumRoll',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='addanddel',
            name='delNum',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='addanddel',
            name='delNumRoll',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
